In [60]:
from subprocess import Popen, PIPE
import os
from tempfile import mkdtemp
from werkzeug import secure_filename
import requests
import gym
from gym import error, spaces, utils
from gym.utils import seeding
from gym import spaces, logger
import subprocess
from subprocess import Popen, PIPE
import numpy as np 
class FooEnv(gym.Env):
    metadata = {'render.modes': ['human']}
    def __init__(self):
        print('__init__')
        self.maxNode = 5 
        self.minNode =1 
        self.cpu_axis  = self.get_cpu_observation()
        self.mem_axis = self.get_mem_observation()
        self.disk_axis = self.get_disk_observation()
        self.net_axis  = self.get_net_observation()
        self.action_space = spaces.Discrete(6)
        high = np.array([
            self.get_cpu_observation(),
            self.get_mem_observation(),
            self.get_disk_observation(),
            self.get_net_observation()])
        low = np.array([
            np.zeros(5),
            np.zeros(5),
            np.zeros(5),
            np.zeros(5)])
        self.observation_space = spaces.Box(low, high, dtype=np.float32)
        self.seed()
        self.obs= 0
        self.obs = self.get_observation()
        self.viewer = None
        self.state = self.get_observation()
        self.attempt = 0 
        self.steps_beyond_done = None
        self.done = False
        self.adapte_cpu= False  
        self.adapte_mem= False 
        self.adapte_disk= False 
        self.adapte_net= False 
        
    def seed(self, seed=None):
        self.np_random, seed = seeding.np_random(seed)
        return [seed]
    
    def step(self, action):
        assert self.action_space.contains(action), "%r (%s) invalid"%(action, type(action))
        state = self.get_observation()
        #past_stat = self.state
        print(state)
        #Find the Utility Prefernces 
        # Select action 
        # get the reward value
       
        maxUtility = np.amax(self.obs[:,4])
        utilityType = np.argmax(self.obs[:,4])
        if utilityType== 0:
            self.adapte_cpu=True 
        elif utilityType== 1:
            self.adapte_mem = True
        elif utilityType== 2:
            self.adapte_disk = True
        elif utilityType== 3:
            self.adapte_net = True
        self.attempt += 1
        if self.adapte_cpu or self.adapte_mem:
            if action == 5:
                print("Scale Down Move to State S1")
                #Reward = max of utility fitness

                response = requests.get(' http://192.168.99.100:5000/services/vscale/web/'+ str(self.attempt) + '/' + str(self.cpu_axis[0])+'/'+str(self.cpu_axis[3]))
                results = response.json()
                if results['result']=='Service converged':
                    done=True       
                    print(results)
                else:
                    done= False
                self.obs = self.get_observation()
                reward= np.amax(self.obs[:,4])  
                print(reward)
                info = "Scale Down Move to State S5"
            elif action == 0:
                print("Stay in State S0")
                self.obs = self.get_observation()
                reward= np.amax(self.obs[:,4])
                if (self.attempt>100):
                    done = True
                else:
                    done= False 
                info = "Stay in State S0"
            elif action == 1: 
                print("Scale Service UP S2")

                response = requests.get(' http://192.168.99.100:5000/services/vscale/web/'+ str(self.attempt) + '/' + str(self.cpu_axis[0])+'/'+str(self.cpu_axis[3]))
                results = response.json()
                if results['result']=='Service converged':
                    done=True 
                else:
                    done= False
                #results = r.json()
                print(results)
                self.obs = self.get_observation()

                #reward= np.amax(self.obs[:,4]) - maxUtility
                reward= np.amax(self.obs[:,4])  
                print(reward)

                info = "Scale Up Move to State S1"

            elif action == 2: 
                print("Mantain Cluster State S0")
                self.obs = self.get_observation()
                reward= np.amax(self.obs[:,4])  
                done= False
                if (self.attempt>100):
                    done = True
                info = "Mantain Cluster State S0"
            elif action == 3: 

                current_state = self.obs

                if (self.attempt > 10 and self.node < self.maxNode and self.node > self.minNode ):
                    print("Add Node S4")
                    filepath = os.path.join('/Users/baz/ieee-demo', 'addNode.sh')
                    print (filepath)
                    res= subprocess.call(filepath, shell=True)
                    print (res)
                    info = "Add Node S4"
                    self.obs = self.get_observation()
                    reward= np.amax(self.obs[:,4])  
                    print("reward: ",reward, np.amax(self.obs[:,4]) ,1-np.amax(self.obs[:,4]))
                    done= True
                    self.node +=1
                else:
                    print("Add Node with attempt: ", self.attempt)
                    done= False
                    self.obs = self.get_observation()
                    reward= np.amax(self.obs[:,4])  
                    print("reward: ",reward, np.amax(self.obs[:,4]) ,1-np.amax(self.obs[:,4]))

            elif action == 4: 

                self.obs = self.get_observation()
                if (self.attempt > 10 and self.node < self.maxNode and self.node > self.minNode ):
                    print("Add Node S4")
                    filepath = os.path.join('/Users/baz/ieee-demo', 'addNode.sh')
                    print (filepath)
                    res= subprocess.call(filepath, shell=True)
                    print (res)
                    info = "Add Node S4"
                    reward= np.amax(self.obs[:,4])  
                    print("reward: ",reward, np.amax(self.obs[:,4]) ,1-np.amax(self.obs[:,4]))
                    done= True
                    self.node +=1
                else:
                    print("Delete Node with attempt: ", self.attempt)
                    done= False
                    reward= np.amax(self.obs[:,4])  
                    print("reward: ",reward, np.amax(self.obs[:,4]) ,1-np.amax(self.obs[:,4]))

        else: 
            print ("action not defined")
            self.obs = self.get_observation()
            done= False
            reward= -1
            info = "action not defined"
        if done: 
            reward = 1.0
        elif self.steps_beyond_done is None:
            #Adaptation Failed 
            reward = 0.0 
            self.steps_beyond_done = 0
        else: 
            if self.steps_beyond_done == 1:
                logger.warn("You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.")
                self.steps_beyond_done += 1
                reward = 0.0
         
        return self.obs, reward, done, {}
    def reset(self):
        self.state = self.get_observation()
        self.steps_beyond_done = None
        self.adapte_cpu= False  
        self.adapte_mem= False 
        self.adapte_disk= False 
        self.adapte_net= False 
        return np.array(self.state)
    def render(self, mode='human', close=False):
        logger.warn("View is not allowed in this environment")
        return 0 
    def close(self):
        if self.viewer:
            self.viewer.close()
            self.viewer = None
    def get_observation(self):
        self.disk_axis =  self.get_cpu_observation() 
        self.mem_axis = self.get_mem_observation()
        self.cpu_axis = self.get_cpu_observation()
        self.net_axis = self.get_net_observation()
        
        obs =np.vstack((self.cpu_axis,self.mem_axis, self.disk_axis, self.net_axis) )
        return obs 
    def get_cpu_observation(self):
        response = requests.get('http://192.168.99.100:8888/cpu', timeout=5)
        results = response.json()
        if len(results) > 0:
                cpu = results['cpu']
                prediction = results['prediction']
                anomalyScore = results['anomalyScore']
                anomalyLikelihood = results['anomalyLikelihood']
                utility_cpu = results['utility_cpu']
                cpu_axis=[cpu, prediction, anomalyScore, anomalyLikelihood, utility_cpu]
        return np.array(cpu_axis) 
    def get_mem_observation(self):
        response = requests.get('http://192.168.99.100:8888/mem', timeout=5)
        results = response.json()
        if len(results) > 0:
            mem = results['mem']
            prediction = results['prediction']
            anomalyScore = results['anomalyScore']
            anomalyLikelihood = results['anomalyLikelihood']
            utility_mem = results['utility_mem']
            #mem_axis=[mem, prediction, anomalyScore, anomalyLikelihood, utility_mem]    
        mem_axis=[mem, prediction, anomalyScore, anomalyLikelihood, utility_mem]
        return np.array(mem_axis) 
    def get_net_observation(self):
        response = requests.get('http://192.168.99.100:8888/net', timeout=5)
        results = response.json()
        if len(results) > 0:
            net = results['net']
            prediction = results['prediction']
            anomalyScore = results['anomalyScore']
            anomalyLikelihood = results['anomalyLikelihood']
            utility_net = results['utility_net']

        net_axis=[net, prediction, anomalyScore, anomalyLikelihood, utility_net]
        return np.array(net_axis) 
    def get_disk_observation(self):
        response = requests.get('http://192.168.99.100:8888/disk', timeout=5)
        if response is not None:
            results = response.json()
            if len(results) > 0:
                disk = results['disk']
                prediction = results['prediction']
                anomalyScore = results['anomalyScore']
                anomalyLikelihood = results['anomalyLikelihood']
                utility_disk = results['utility_disk']
                #disk_axis=[disk, prediction, anomalyScore, anomalyLikelihood, utility_disk]
                disk_axis=[0, 0, 0, 0, 0]
        return np.array(disk_axis) 
  
    def get_current_state(self):
        current_state = self.state
         
        return current_state

In [61]:
env = FooEnv()

__init__


In [62]:
env.reset()

array([[13.92969161, 13.92969161,  1.        ,  0.5       ,  6.9648458 ],
       [34.14543512, 34.14543512,  1.        ,  0.5       , 17.07271756],
       [13.92969161, 13.92969161,  1.        ,  0.5       ,  6.9648458 ],
       [70.96379984, 70.96379984,  1.        ,  0.5       , 35.48189992]])

In [71]:
print(env.adapte_cpu, 
        env.adapte_mem,
        env.adapte_disk, 
        env.adapte_net)

False True False True


In [70]:
env.info

AttributeError: 'FooEnv' object has no attribute 'info'

In [15]:
env.step(1)

[[10.44083527 10.44083527  1.          0.5         5.22041763]
 [17.27336051 17.27336051  1.          0.5         8.63668025]
 [10.44083527 10.44083527  1.          0.5         5.22041763]
 [68.9379292  68.9379292   1.          0.5        34.4689646 ]]
Scale Service UP S2
{'previous_replicas': '8', 'result': 'Service converged', 'Replicas': '7'}
34.46896459763984


(array([[10.44083527, 10.44083527,  1.        ,  0.5       ,  5.22041763],
        [17.27336051, 17.27336051,  1.        ,  0.5       ,  8.63668025],
        [10.44083527, 10.44083527,  1.        ,  0.5       ,  5.22041763],
        [68.9379292 , 68.9379292 ,  1.        ,  0.5       , 34.4689646 ]]),
 1.0,
 True,
 {})

In [70]:
env.reset()
for i in range(10):
   
    time.sleep(6)
    print(env.state)
    print("========")
    print(env.cpu_axis)

[[70.50068861 70.50068861  1.          0.5        35.25034431]
 [58.70992976 58.70992976  1.          0.5        29.35496488]
 [70.50068861 70.50068861  1.          0.5        35.25034431]
 [ 0.          0.          1.          0.5         0.        ]]
[70.50068861 70.50068861  1.          0.5        35.25034431]
[[70.50068861 70.50068861  1.          0.5        35.25034431]
 [58.70992976 58.70992976  1.          0.5        29.35496488]
 [70.50068861 70.50068861  1.          0.5        35.25034431]
 [ 0.          0.          1.          0.5         0.        ]]
[70.50068861 70.50068861  1.          0.5        35.25034431]
[[70.50068861 70.50068861  1.          0.5        35.25034431]
 [58.70992976 58.70992976  1.          0.5        29.35496488]
 [70.50068861 70.50068861  1.          0.5        35.25034431]
 [ 0.          0.          1.          0.5         0.        ]]
[70.50068861 70.50068861  1.          0.5        35.25034431]
[[70.50068861 70.50068861  1.          0.5        35.25

In [72]:
%%time
env.reset()
for i in range(5):
    env.step(i)
    env.attempt

[[16.75691519 16.75691519  1.          0.5         8.37845759]
 [34.29184001 34.29184001  1.          0.5        17.14592001]
 [16.75691519 16.75691519  1.          0.5         8.37845759]
 [ 0.          0.          1.          0.5         0.        ]]
Stay in State S0
[[16.60555963 16.60555963  1.          0.5         8.30277981]
 [34.30013126 34.30013126  1.          0.5        17.15006563]
 [16.60555963 16.60555963  1.          0.5         8.30277981]
 [ 0.          0.          1.          0.5         0.        ]]
Scale Service UP S2
{'previous_replicas': '3', 'result': 'Service converged', 'Replicas': '2'}
24.36682455274144
[[15.51370398 15.51370398  1.          0.5         7.75685199]
 [34.39006052 34.39006052  1.          0.5        17.19503026]
 [15.51370398 15.51370398  1.          0.5         7.75685199]
 [48.73364911 48.73364911  1.          0.5        24.36682455]]
Mantain Cluster State S0
[[15.51370398 15.51370398  1.          0.5         7.75685199]
 [34.39006052 34.390060

In [6]:
%%time
env.reset()
for i in range(11):
    env.step(5)
    env.attempt

[[  9.23113687   9.23113687   1.           0.5          4.61556843]
 [ 36.70254495  36.70254495   1.           0.5         18.35127247]
 [  9.23113687   9.23113687   1.           0.5          4.61556843]
 [367.34966295 367.34966295   1.           0.5        183.67483148]]
Scale Down Move to State S1
<Response [200]>
0.0
[[  9.23113687   9.23113687   1.           0.5          4.61556843]
 [ 36.70254495  36.70254495   1.           0.5         18.35127247]
 [  9.23113687   9.23113687   1.           0.5          4.61556843]
 [367.34966295 367.34966295   1.           0.5        183.67483148]]
Scale Down Move to State S1
<Response [200]>
0.0
[[  9.23113687   9.23113687   1.           0.5          4.61556843]
 [ 36.70254495  36.70254495   1.           0.5         18.35127247]
 [  9.23113687   9.23113687   1.           0.5          4.61556843]
 [367.34966295 367.34966295   1.           0.5        183.67483148]]
Scale Down Move to State S1
<Response [200]>
0.0
[[  9.23113687   9.23113687   1.  

In [ ]:
def get_cpu_observation():
        response = requests.get('http://192.168.99.100:8888/cpu', timeout=5)
        results = response.json()
        if len(results) > 0:
                cpu = results['cpu']
                prediction = results['prediction']
                anomalyScore = results['anomalyScore']
                anomalyLikelihood = results['anomalyLikelihood']
                utility_cpu = results['utility_cpu']
                cpu_axis=[cpu, prediction, anomalyScore, anomalyLikelihood, utility_cpu]
        return np.array(cpu_axis) 

In [ ]:
cpu = get_cpu_observation()
cpu.shape

In [ ]:

params = {'Username':'admin', 'Password':'admin1234'}
response = requests.post('http://192.168.99.100:9000/api/auth', data=params, timeout=5)
results = response.json()
print(results)

In [ ]:
import json 


In [ ]:
def authSwarm():
    payload = {'Username':'admin','Password':'admin1234'}
    headers = {'content-type': 'application/json'}
    r = requests.post('http://192.168.99.100:9000/api/auth', data=json.dumps(payload),headers=headers)
    r.json()
    return r.json()
    

In [ ]:
t = authSwarm()
t['jwt']

In [ ]:
def listContainer():
    payload = {'all':'true'}
    headers = {'content-type': 'application/json', 'Authorization':'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOjEsImV4cCI6MTU0NTEyNjExMn0.wzp6XzgUAXWiUazrdYyJ9Q6riV_cQQSGZqbivxF1zzA'}
    r = requests.get('http://192.168.99.100:9000/api/webhooks/6d3de54e-d6ca-4cc8-b53b-f758c9bb419a')
    r.json()
    return r.json()

In [ ]:
r = requests.get('http://192.168.99.100:9000/api/webhooks/6d3de54e-d6ca-4cc8-b53b-f758c9bb419a')

r.content

In [ ]:
http GET :9000/api/endpoints/1/docker/containers/json \
"Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOjEsImV4cCI6MTU0NTEyNjExMn0.wzp6XzgUAXWiUazrdYyJ9Q6riV_cQQSGZqbivxF1zzA" \
all==true