In [1]:
from __future__ import division, print_function, unicode_literals
import csv
import shutil
import os
import time
import requests
import subprocess
from subprocess import call
import numpy as np
import tensorflow as tf


In [2]:
import numpy as np
import gym

from keras.models import Sequential
from keras.layers import Dense, Activation, Flatten
from keras.optimizers import Adam

from rl.agents.dqn import DQNAgent
from rl.policy import BoltzmannQPolicy
from rl.memory import SequentialMemory 

Using TensorFlow backend.


In [3]:
def reset_graph(seed=42):
    tf.reset_default_graph()
    tf.set_random_seed(seed)
    np.random.seed(seed)

In [4]:
def save_fig(fig_id, tight_layout=True):
    path = os.path.join(PROJECT_ROOT_DIR, "images", CHAPTER_ID, fig_id + ".png")
    print("Saving figure", fig_id)
    if tight_layout:
        plt.tight_layout()
    plt.savefig(path, format='png', dpi=300)

# # # MDP 


## Deep Q-Learning


In [5]:
import gym
import gym_foo

In [6]:
env = gym.make('foo-v9')

__init__


KeyError: 'utility_disk'

In [7]:
env.observation_space.shape

NameError: name 'env' is not defined

In [24]:
nb_actions= env.action_space.n
nb_actions

6

In [25]:
env.node

0

In [10]:
# Next, we build a very simple model.
model = Sequential()
model.add(Flatten(input_shape=(1,) + env.observation_space.shape))
model.add(Dense(16))
model.add(Activation('relu'))
model.add(Dense(16))
model.add(Activation('relu'))
model.add(Dense(16))
model.add(Activation('relu'))
model.add(Dense(nb_actions))
model.add(Activation('linear'))

In [11]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_1 (Flatten)          (None, 20)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 16)                336       
_________________________________________________________________
activation_1 (Activation)    (None, 16)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 16)                272       
_________________________________________________________________
activation_2 (Activation)    (None, 16)                0         
_________________________________________________________________
dense_3 (Dense)              (None, 16)                272       
_________________________________________________________________
activation_3 (Activation)    (None, 16)                0         
__________

In [12]:
memory = SequentialMemory(limit=1000, window_length=1)
policy = BoltzmannQPolicy()
dqn = DQNAgent(model=model, nb_actions=nb_actions, memory=memory, nb_steps_warmup=10,
               target_model_update=1e-2, policy=policy)
dqn.compile(Adam(lr=1e-3), metrics=['mae'])

In [13]:
dqn.fit(env, nb_steps=1000, visualize=False, verbose=2)


Training for 10 steps ...
[[1.60222222e+01 1.60222222e+01 1.00000000e+00 5.00000000e-01
  8.01111111e+00]
 [3.48462539e+01 3.48462539e+01 1.00000000e+00 5.00000000e-01
  1.74231270e+01]
 [1.60222222e+01 1.60222222e+01 1.00000000e+00 5.00000000e-01
  8.01111111e+00]
 [6.11646667e+03 6.11646667e+03 1.00000000e+00 5.00000000e-01
  3.05823333e+03]]
action not defined
[[ 16.02222222  16.02222222   1.           0.5          8.01111111]
 [ 34.84625395  34.84625395   1.           0.5         17.42312697]
 [ 16.02222222  16.02222222   1.           0.5          8.01111111]
 [106.99398336 106.99398336   1.           0.5         53.49699168]]
action not defined
[[16.02222222 16.02222222  1.          0.5         8.01111111]
 [34.84625395 34.84625395  1.          0.5        17.42312697]
 [16.02222222 16.02222222  1.          0.5         8.01111111]
 [49.71152421 49.71152421  1.          0.5        24.85576211]]
action not defined
[[16.02222222 16.02222222  1.          0.5         8.01111111]
 [34.84

In [16]:
# Okay, now it's time to learn something! We visualize the training here for show, but this
# slows down training quite a lot. You can always safely abort the training prematurely using
# Ctrl + C.
ENV_NAME="micro2"
dqn.fit(env, nb_steps=1000, visualize=True, verbose=2)

# After training is done, we save the final weights.
dqn.save_weights('dqn_{}_weights.h5f'.format(ENV_NAME), overwrite=True)

# Finally, evaluate our algorithm for 5 episodes.
dqn.test(env, nb_episodes=5, visualize=True)

Training for 50 steps ...


JSONDecodeError: Extra data: line 1 column 5 (char 4)